### ISSUE TITLE
Integration doesn't start up since v1.17

### ISSUE THREAD

**Issue by hundehausen** [ualex73/monitor_docker#150]
```
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 12:29:56 (1 occurrences)
Last logged: 12:29:56

Error during setup of component monitor_docker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/monitor_docker/__init__.py", line 141, in async_setup
    entry[CONF_MONITORED_CONDITIONS].remove(CONTAINER_INFO_ALLINONE)
ValueError: list.remove(x): x not in list
``` 

This is my config, that has worked before:

```
monitor_docker:
  - name: Docker-NAS
    url: tcp://192.168.1.60:2376
  - name: Docker-PI3
    url: tcp://192.168.1.50:2375
  - name: Docker-MAIN
  ```

**Comment by ualex73** [comment]
Fixed is in the latest master, thanks for reporting it.
