### ISSUE TITLE
Error during setup of component monitor_docker

### ISSUE THREAD

**Issue by khensel17** [ualex73/monitor_docker#34]
HA version: 0.114.4
Using version 1.4 and installed with HACS

HA is unable to setup the custom_component:
```yaml
Logger: homeassistant.setup
Source: custom_components/monitor_docker/__init__.py:91
First occurred: 11:02:15 AM (1 occurrences)
Last logged: 11:02:15 AM

Error during setup of component monitor_docker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/monitor_docker/__init__.py", line 91, in async_setup
    for entry in config[DOMAIN]:
KeyError: 'monitor_docker'
```

**Comment by ualex73** [comment]
Can you share your yaml configuration?

**Comment by khensel17** [comment]
```yaml
sensor:
- platform: monitor_docker
  url: tcp://xxx.xxx.xxx.xxx:2375
  containers:
    - reverse_proxy
    - openvpn-as
    - unifi-controller
    - mosquitto_mosquitto_1
  monitored_conditions:
    - utilization_version
    - container_status
    - container_memory_usage
    - container_memory_percentage_usage
    - container_cpu_percentage_usage

**Comment by ualex73** [comment]
Ok, the configuration is wrong. The "monitor_docker" is not a sensor, it is a platform component. so you need to define it as:

```
monitor_docker:
  - name: Docker
    url: tcp://xxx.xxx.xxx.xxx:2375
    containers:
      - reverse_proxy
      - openvpn-as
      - unifi-controller
      - mosquitto_mosquitto_1
    monitored_conditions:
      - utilization_version
      - container_status
      - container_memory_usage
      - container_memory_percentage_usage
      - container_cpu_percentage_usage
```

**Comment by khensel17** [comment]
Thanks for checking the issue. I mixed my config with an old component.
I solved it now.
