### ISSUE TITLE
[BUG] Sensor property renamed in 2021.12.0+

### ISSUE THREAD

**Issue by firstof9** [ualex73/monitor_docker#82]
Error:
```
(<class 'custom_components.monitor_docker.sensor.DockerSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

`device_state_attributes` needs to be changed to `extra_state_attributes`.

**Comment by ualex73** [comment]
Thanks for reporting, can you try out v1.13-beta2?

**Comment by firstof9** [comment]
Trying it out now.

**Comment by firstof9** [comment]
```log
2021-12-06 06:46:15 ERROR (MainThread) [homeassistant.components.switch] Error while setting up monitor_docker platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/monitor_docker/switch.py", line 109, in async_setup_platform
    if includeContainer:
UnboundLocalError: local variable 'includeContainer' referenced before assignment
2021-12-06 06:46:15 ERROR (MainThread) [homeassistant.components.switch] Error while setting up monitor_docker platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/monitor_docker/switch.py", line 109, in async_setup_platform
    if includeContainer:
UnboundLocalError: local variable 'includeContainer' referenced before assignment
```

**Comment by firstof9** [comment]
Looks good no errors.
Cheers! 🍻

**Comment by ualex73** [comment]
Cool :-) Then i will release this v1.13-beta3 soon as an official one.

Op ma 6 dec. 2021 om 15:00 schreef Chris ***@***.***>:
